spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:~/creport
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 10MB
           
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: always

    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        
security:
    oauth2:
        client:
            clientId: 989032708997-4mogdf4q7llvtculjgfr7rvm3beban64.apps.googleusercontent.com
            clientSecret: 3Njkpi3MnLyC4fhgjhp-lCMS
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: 
              - https://www.googleapis.com/auth/spreadsheets.readonly
              - https://www.googleapis.com/auth/gmail.send
              - profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me

applicationName: ComplianceReportGeneratorClient